// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a raw file and create a new session.
 * 
 * Decodes the file via LibRaw, creates a BayerDataStore,
 * and returns SessionInfo to the frontend.
 */
async openFile(path: string) : Promise<Result<SessionInfo, RawViewError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Standard 2×2 Bayer pattern variants.
 * Named by the top-left 2×2 arrangement.
 */
export type BayerPattern = 
/**
 * R G / G B
 */
"Rggb" | 
/**
 * B G / G R
 */
"Bggr" | 
/**
 * G R / B G
 */
"Grbg" | 
/**
 * G B / R G
 */
"Gbrg"
/**
 * The CFA pattern of the sensor.
 */
export type CfaPattern = 
/**
 * Standard 2×2 Bayer pattern
 */
{ type: "Bayer"; pattern: BayerPattern } | 
/**
 * Fuji X-Trans 6×6 pattern
 */
{ type: "XTrans"; grid: [([number, number, number, number, number, number]), ([number, number, number, number, number, number]), ([number, number, number, number, number, number]), ([number, number, number, number, number, number]), ([number, number, number, number, number, number]), ([number, number, number, number, number, number])] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Application error enum covering all failure modes.
 * Maps to FR6 categorized error taxonomy.
 */
export type RawViewError = 
/**
 * File format not recognized by LibRaw
 */
{ type: "UnsupportedFormat"; extension: string } | 
/**
 * File exists but contains corrupt or unreadable raw data
 */
{ type: "CorruptData"; detail: string } | 
/**
 * File cannot be read (permissions, not found, etc.)
 */
{ type: "FileAccessDenied"; path: string } | 
/**
 * LibRaw decoder returned an error
 */
{ type: "DecoderError"; source: string } | 
/**
 * Viewport rendering failed
 */
{ type: "RenderError"; detail: string } | 
/**
 * Referenced session no longer exists
 */
{ type: "SessionExpired"; session_id: string }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
/**
 * Information sent to the frontend after opening a file.
 */
export type SessionInfo = { session_id: string; filename: string; width: number; height: number; cfa_pattern: CfaPattern; bit_depth: number; black_level: number; white_level: number; iso: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
